apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: app-git
spec:
  type: git
  params:
    - name: revision
      value: main
    - name: url
      value: https://github.com/hsaid4327/basic-tekton-pipeline.git #configure: change if you want to build something else, perhaps from your own local git repository.
